services:
  barracuda-camera:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda-camera
    privileged: true
    tty: true
    network_mode: host
    runtime: nvidia
    volumes:
      - $HOME/.ssh:/root/.ssh
    environment:
      - DISPLAY
